import type { Metadata } from 'next'

import './globals.css'

import AuthProvider from '@/provider/auth-provider'

import { poppins, roboto } from './fonts'

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

interface Children {
   children: React.ReactNode
}

export default function RootLayout({ children }: Readonly<Children>) {
   return (
      <html lang="en" className={`${poppins.variable} ${roboto.variable}`}>
         <body>
            <AuthProvider>{children}</AuthProvider>
         </body>
      </html>
   )
}
